# Generated by Django 3.2 on 2021-04-12 16:22

from django.db import migrations, models
import member.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=50)),
                ('last_name', models.CharField(help_text='Last Name', max_length=50)),
                ('username', models.CharField(help_text='Username', max_length=50, unique=True)),
                ('password', models.CharField(help_text='Password', max_length=100, validators=[member.validators.password_len_validator])),
                ('post', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=50, verbose_name='Designation')),
                ('mail', models.EmailField(max_length=100, unique=True, verbose_name='E-Mail')),
                ('phone', models.IntegerField(help_text='Phone No. (10 digits)', unique=True, validators=[member.validators.phone_number_validator])),
                ('current', models.CharField(max_length=50)),
            ],
        ),
    ]
