# Generated by Django 3.2 on 2021-04-10 16:04

from django.db import migrations, models
import member.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100, validators=[member.validators.password_len_validator])),
                ('post', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=50)),
                ('mail', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(validators=[member.validators.phone_number_validator])),
            ],
        ),
    ]
