# Generated by Django 3.2 on 2021-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='current',
            field=models.CharField(default='inactive', max_length=50),
        ),
    ]
