# Generated by Django 3.2 on 2021-04-11 08:49

from django.db import migrations, models
import member.validators


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(unique=True, validators=[member.validators.phone_number_validator]),
        ),
    ]
