# Generated by Django 3.2 on 2021-04-11 08:54

from django.db import migrations, models
import member.validators


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210411_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(help_text='E-Mail', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(help_text='Password', max_length=100, validators=[member.validators.password_len_validator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(help_text='Phone No. (10 digits)', unique=True, validators=[member.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(help_text='Username', max_length=50, unique=True),
        ),
    ]
